name: merged
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  connectivity_plus: ^4.0.0
  shared_preferences: ^2.1.0
  flutter_lints: ^2.0.0
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

 